services:
  backend:
    build: ./backend
    environment:
      SPRING_PROFILES_ACTIVE: mock
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
